first_linewidth: 5
distance_from_outer_ring: 50
first_section_height: 573
first_section_width: 155
# first_section_back_height: 29.5
#
first_section_back_height: 101
#
second_section_linewidth: 4.5
# second_section_top_width1: 19.25
# second_section_top_height1: 34.5
# second_section_top_width2: 23.5
# second_section_top_height2: 29.5
# second_section_top_width3: 33
# second_section_top_height3: 36
# second_section_top_width4: 20.5
# second_section_top_height4: 36
# second_section_top_width5: 25.25
#
second_section_top_width1: 22.25
second_section_top_height1: 61
second_section_top_width2: 44.5
second_section_top_height2: 61
second_section_top_width3: 22.25
second_section_top_height3: 0
second_section_top_width4: 0
second_section_top_height4: 0
second_section_top_width5: 0
#
# second_section_bot_width1: 24
# second_section_bot_height1: 34.5
# second_section_bot_width2: 27.5
# second_section_bot_height2: 34.5
# second_section_bot_width3: 20.5
# second_section_bot_height3: 34.5
# second_section_bot_width4: 27.5
# second_section_bot_height4: 34.5
# second_section_bot_width5: 22.25
#
second_section_bot_width1: 22.25
second_section_bot_height1: 61
second_section_bot_width2: 44.5
second_section_bot_height2: 61
second_section_bot_width3: 22.25
second_section_bot_height3: 0
second_section_bot_width4: 0
second_section_bot_height4: 0
second_section_bot_width5: 0
#
start_of_second_section_vertical_linewidth: 3.5
end_of_second_section_vertical_linewidth: 5
#
# third_section_linewidth: 3
# third_section_width1: 14.5
# third_section_height1: 105
# third_section_width2: 23
# third_section_height2: 105
# third_section_width3: 16
#
third_section_linewidth: 3
third_section_width1: 21.5
third_section_height1: 50
third_section_width2: 43
third_section_height2: 50
third_section_width3: 23
#
meander_height: 525
meander_linewidth: 5
meander_initial_gap: 20
no_of_full_straights: 10
meander_final_gap: 15
meander_gap_spacing: 10
meander_to_frame_box_size: 10
meander_last_fork_top_box_size: 11
meander_last_fork_via_box_size_x: 13
meander_last_fork_via_box_size_y: 11
meander_last_fork_via_box_y_offset: 1
meander_conect_linewidth: 5
meander_conect_bot_width: 25
meander_conect_right_height: 260
meander_conect_final_width: 7.5
meander_last_fork_wdith: 3
meander_last_fork_height: 250
meander_last_fork_linewdith: 2.5
meander_last_fork_start_height: 14
conection_to_kid_path_linewidth: 5
conection_to_kid_path_start_piece_length: 10
