outer_box_width: 100
outer_box_height: 100
outer_box_inner_cutout_width: 27
outer_box_inner_cutout_height: 12
linewidth: 5
half_conect_taper_extra_height: 5
half_conect_taper_stright_width: 5
half_conect_taper_diag_width: 5.5
half_conect_taper_inner_height: 4
half_conect_distacne_from_center: 5
half_conect_bridge_rect_width: 21
half_conect_bridge_rect_height: 4
half_conect_bridge_pad_width: 5.5
half_conect_bridge_pad_height: 4
half_conect_bridge_pad_offset_from_center: 5
full_conect_taper_extra_width: 5
full_conect_taper_stright_height: 5
full_conect_taper_diag_height: 5.5
full_conect_taper_start_from_center: 4
full_conect_center_width: 4
