Hi_pass_arm1_linewidth: 22
Hi_pass_arm1_height: 23
Hi_pass_arm1_length: 97
Hi_pass_arm1_offset: 141
Hi_pass_arm2_linewidth: 42
Hi_pass_arm2_height: 34
Hi_pass_arm2_length: 77
Hi_pass_arm2_offset: 134
Hi_pass_arm3_linewidth: 42
Hi_pass_arm3_height: 34
Hi_pass_arm3_length: 77
Hi_pass_arm3_offset: 124
Hi_pass_arm4_linewidth: 42
Hi_pass_arm4_height: 34
Hi_pass_arm4_length: 77
Hi_pass_arm4_offset: 124
Hi_pass_arm5_linewidth: 22
Hi_pass_arm5_height: 23
Hi_pass_arm5_length: 97
Hi_pass_arm5_offset: 114
via_overlap_length: 5
via_extend_length: 3
