Lo_pass_arm1_linewidth: 10
Lo_pass_arm1_height: 20
Lo_pass_arm1_length: 170
Lo_pass_arm1_offset: 139
Lo_pass_arm2_linewidth: 20
Lo_pass_arm2_height: 41
Lo_pass_arm2_length: 160
Lo_pass_arm2_offset: 255
Lo_pass_arm3_linewidth: 20
Lo_pass_arm3_height: 41
Lo_pass_arm3_length: 160
Lo_pass_arm3_offset: 215
Lo_pass_arm4_linewidth: 20
Lo_pass_arm4_height: 41
Lo_pass_arm4_length: 160
Lo_pass_arm4_offset: 215
Lo_pass_arm5_linewidth: 10
Lo_pass_arm5_height: 41
Lo_pass_arm5_length: 170
Lo_pass_arm5_offset: 210
via_overlap_length: 5
via_extend_length: 5
