test_chip_quad_width: 27000
test_chip_quad_height: 27000
chip_to_holder_bend_rad: 2500
chip_to_holder_feedline_width: 500
chip_to_holder_cutout_around_feedline_width: 1620
chip_to_holder_dielectric_under_feedline_width: 1740
chip_to_holder_port_extend: 4000
chip_to_holder_holder_extend: 10000
chip_to_holder_end_cutout_distance: 4000
chip_to_holder_end_cutout_center_distance: 700
horn_offset_from_center_x: 6000
horn_offset_from_center_y: 6000
top_right_label_window_offset_x: 2000
top_right_label_window_offset_y: 1200
top_right_label_window_width: 4000
top_right_label_window_height: 1000
bottom_left_text_offset_x: 1000
bottom_left_text_offset_y: 1000
bottom_left_text_size: 300
top_right_text_offset_x: 1000
top_right_text_offset_y: 1000
top_right_text_size: 300
top_left_text_offset_x: 1000
top_left_text_offset_y: 1000
top_left_text_size: 300
cardiff_logo_size: 2000
cardiff_logo_offset_x: 1000
cardiff_logo_offset_y: 1000
souk_logo_size: 2600
souk_logo_offset_x: 3500
souk_logo_offset_y: 700
groundplane_edge_cuts_top_mid_gap: 5500
groundplane_edge_cuts_bot_mid_gap: 5500
groundplane_edge_cuts_right_mid_gap: 0
groundplane_edge_cuts_left_mid_gap: 0
center_pin_radius: 1010
slotted_pin_radius: 1010
slotted_pin_length: 500
slotted_pin_offset_x_from_center_pin: 8000
slotted_pin_offset_y_from_center_pin: 0
